// Курируемая библиотека упражнений — перенесена из демо-версии
// (project_gym/src/data/exercises.ts) один в один, чтобы у зала сразу
// был осмысленный справочник вместо пустого списка.
//
// Фотографии упражнений: локальный архив th_exercises, файлы лежат в
// web/public/exercises/new/NNN.jpg (часть упражнений осталась на старых
// фото wger.de, CC-BY-SA). Упражнения без фото используют плейсхолдер
// на фронтенде.
import { MuscleGroup } from '@prisma/client';

export interface ExerciseSeed {
  name: string;
  muscleGroup: MuscleGroup;
  defaultSets: number;
  defaultReps: string;
  defaultLoad: string;
  technique: string;
  equipment: string;
  imageUrl?: string;
  imageAttribution?: string;
}

export const EXERCISE_LIBRARY: ExerciseSeed[] = [
  { name: 'Жим штанги лёжа', muscleGroup: 'CHEST', defaultSets: 4, defaultReps: '8-10', defaultLoad: '60 кг', technique: 'Лопатки сведены, гриф опускается к нижней части груди, локти ~45° от корпуса.', equipment: 'Штанга, скамья', imageUrl: 'exercises/new/001.jpg' },
  { name: 'Жим гантелей на наклонной скамье', muscleGroup: 'CHEST', defaultSets: 4, defaultReps: '10-12', defaultLoad: '22 кг', technique: 'Наклон скамьи 30-45°, гантели сводятся вверху без удара друг о друга.', equipment: 'Гантели, скамья', imageUrl: 'exercises/new/004.jpg' },
  { name: 'Разведение гантелей лёжа', muscleGroup: 'CHEST', defaultSets: 3, defaultReps: '12-15', defaultLoad: '10 кг', technique: 'Лёгкий изгиб в локтях сохраняется на всей амплитуде, растяжка без боли в плече.', equipment: 'Гантели, скамья', imageUrl: 'exercises/new/007.jpg' },
  { name: 'Отжимания на брусьях', muscleGroup: 'CHEST', defaultSets: 3, defaultReps: '10-15', defaultLoad: 'вес тела', technique: 'Корпус с наклоном вперёд для акцента на грудь, локти в стороны.', equipment: 'Брусья', imageUrl: 'exercises/new/006.jpg' },
  { name: 'Сведение рук в кроссовере', muscleGroup: 'CHEST', defaultSets: 3, defaultReps: '12-15', defaultLoad: '15 кг', technique: 'Сведение по дуге перед собой, пиковое сокращение 1 сек.', equipment: 'Кроссовер', imageUrl: 'exercises/new/008.jpg' },
  { name: 'Отжимания от пола', muscleGroup: 'CHEST', defaultSets: 3, defaultReps: '15-20', defaultLoad: 'вес тела', technique: 'Корпус прямой, локти под углом 45°, грудь почти касается пола.', equipment: '-', imageUrl: 'exercises/new/009.jpg' },
  { name: 'Становая тяга', muscleGroup: 'BACK', defaultSets: 4, defaultReps: '6-8', defaultLoad: '80 кг', technique: 'Спина прямая, гриф скользит вдоль голени, тяга за счёт ног и ягодиц.', equipment: 'Штанга', imageUrl: 'exercises/new/011.jpg' },
  { name: 'Подтягивания широким хватом', muscleGroup: 'BACK', defaultSets: 4, defaultReps: '6-10', defaultLoad: 'вес тела', technique: 'Подбородок выше перекладины, лопатки сведены в верхней точке.', equipment: 'Турник', imageUrl: 'exercises/new/012.jpg' },
  { name: 'Тяга штанги в наклоне', muscleGroup: 'BACK', defaultSets: 4, defaultReps: '8-10', defaultLoad: '50 кг', technique: 'Корпус ~45° к полу, тяга к низу живота, без рывка.', equipment: 'Штанга', imageUrl: 'exercises/new/014.jpg' },
  { name: 'Тяга верхнего блока', muscleGroup: 'BACK', defaultSets: 3, defaultReps: '10-12', defaultLoad: '45 кг', technique: 'Тяга к верху груди, локти вниз, без раскачки корпуса.', equipment: 'Блочный тренажёр', imageUrl: 'exercises/new/072.jpg' },
  { name: 'Горизонтальная тяга блока', muscleGroup: 'BACK', defaultSets: 3, defaultReps: '10-12', defaultLoad: '50 кг', technique: 'Спина прямая, тяга рукояти к животу, лопатки сводятся в конце.', equipment: 'Блочный тренажёр', imageUrl: 'exercises/new/093.jpg' },
  { name: 'Гиперэкстензия', muscleGroup: 'BACK', defaultSets: 3, defaultReps: '15-20', defaultLoad: 'вес тела', technique: 'Подъём корпуса до прямой линии, без переразгибания поясницы.', equipment: 'Скамья для гиперэкстензии', imageUrl: 'exercises/new/019.jpg' },
  { name: 'Приседания со штангой', muscleGroup: 'LEGS', defaultSets: 4, defaultReps: '8-10', defaultLoad: '70 кг', technique: 'Колени по направлению носков, таз назад-вниз, бёдра параллельно полу.', equipment: 'Штанга, стойки', imageUrl: 'exercises/new/091.jpg' },
  { name: 'Жим ногами в тренажёре', muscleGroup: 'LEGS', defaultSets: 4, defaultReps: '10-12', defaultLoad: '120 кг', technique: 'Колени не заходят за носки, полная амплитуда без отрыва таза.', equipment: 'Тренажёр', imageUrl: 'exercises/new/025.jpg' },
  { name: 'Румынская тяга', muscleGroup: 'LEGS', defaultSets: 3, defaultReps: '10-12', defaultLoad: '50 кг', technique: 'Ноги почти прямые, штанга скользит по бедру, растяжка задней поверхности.', equipment: 'Штанга', imageUrl: 'exercises/new/023.jpg' },
  { name: 'Выпады с гантелями', muscleGroup: 'LEGS', defaultSets: 3, defaultReps: '12 на ногу', defaultLoad: '14 кг', technique: 'Колено передней ноги над носком, заднее колено почти касается пола.', equipment: 'Гантели', imageUrl: 'exercises/new/090.jpg' },
  { name: 'Сгибание ног лёжа', muscleGroup: 'LEGS', defaultSets: 3, defaultReps: '12-15', defaultLoad: '35 кг', technique: 'Таз плотно прижат к скамье, сгибание без рывка.', equipment: 'Тренажёр', imageUrl: 'exercises/new/089.jpg' },
  { name: 'Разгибание ног сидя', muscleGroup: 'LEGS', defaultSets: 3, defaultReps: '12-15', defaultLoad: '40 кг', technique: 'Разгибание до полного выпрямления, пауза 1 сек в верхней точке.', equipment: 'Тренажёр', imageUrl: 'exercises/new/026.jpg' },
  { name: 'Подъём на носки стоя', muscleGroup: 'LEGS', defaultSets: 4, defaultReps: '15-20', defaultLoad: '40 кг', technique: 'Полная амплитуда, растяжка икры внизу, пауза вверху.', equipment: 'Тренажёр Смита', imageUrl: 'exercises/new/033.jpg' },
  { name: 'Гоблет-приседания', muscleGroup: 'LEGS', defaultSets: 3, defaultReps: '12-15', defaultLoad: '16 кг', technique: 'Гиря/гантель у груди, локти внутри колен в нижней точке.', equipment: 'Гиря', imageUrl: 'exercises/new/021.jpg' },
  { name: 'Жим гантелей сидя', muscleGroup: 'SHOULDERS', defaultSets: 4, defaultReps: '8-10', defaultLoad: '16 кг', technique: 'Спина плотно к скамье, гантели не сталкиваются в верхней точке.', equipment: 'Гантели, скамья', imageUrl: 'exercises/new/036.jpg' },
  { name: 'Махи гантелями в стороны', muscleGroup: 'SHOULDERS', defaultSets: 3, defaultReps: '12-15', defaultLoad: '8 кг', technique: 'Лёгкий изгиб локтей, подъём до уровня плеч без рывка.', equipment: 'Гантели', imageUrl: 'exercises/new/037.jpg' },
  { name: 'Жим штанги стоя', muscleGroup: 'SHOULDERS', defaultSets: 4, defaultReps: '8-10', defaultLoad: '35 кг', technique: 'Пресс напряжён, гриф движется строго вертикально мимо лица.', equipment: 'Штанга', imageUrl: 'exercises/new/043.jpg' },
  { name: 'Тяга штанги к подбородку', muscleGroup: 'SHOULDERS', defaultSets: 3, defaultReps: '10-12', defaultLoad: '25 кг', technique: 'Локти ведут движение и идут выше кистей.', equipment: 'Штанга', imageUrl: 'exercises/new/088.jpg' },
  { name: 'Махи в наклоне на задние дельты', muscleGroup: 'SHOULDERS', defaultSets: 3, defaultReps: '12-15', defaultLoad: '6 кг', technique: 'Корпус параллельно полу, махи назад-в стороны.', equipment: 'Гантели', imageUrl: 'exercises/new/039.jpg' },
  { name: 'Подъём штанги на бицепс', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '10-12', defaultLoad: '25 кг', technique: 'Локти прижаты к корпусу, без раскачки, полная амплитуда.', equipment: 'Штанга', imageUrl: 'exercises/new/045.jpg' },
  { name: 'Молотковые сгибания', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '12', defaultLoad: '12 кг', technique: 'Нейтральный хват, локти статичны, движение только в предплечье.', equipment: 'Гантели', imageUrl: 'exercises/new/047.jpg' },
  { name: 'Французский жим', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '10-12', defaultLoad: '20 кг', technique: 'Локти неподвижны, гриф опускается за голову, растяжка трицепса.', equipment: 'EZ-гриф', imageUrl: 'exercises/new/087.jpg' },
  { name: 'Разгибание рук на блоке', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '12-15', defaultLoad: '25 кг', technique: 'Локти прижаты к корпусу, полное разгибание с паузой.', equipment: 'Блочный тренажёр', imageUrl: 'exercises/new/086.jpg' },
  { name: 'Отжимания узким хватом', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '12-15', defaultLoad: 'вес тела', technique: 'Кисти под грудью, локти движутся вдоль корпуса.', equipment: '-', imageUrl: 'exercises/new/085.jpg' },
  { name: 'Скручивания на римском стуле', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '15-20', defaultLoad: 'вес тела', technique: 'Скручивание за счёт пресса, поясница прижата.', equipment: 'Скамья', imageUrl: 'exercises/new/073.jpg' },
  { name: 'Подъём ног в висе', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '12-15', defaultLoad: 'вес тела', technique: 'Подъём без раскачки, таз слегка подкручивается вверху.', equipment: 'Турник', imageUrl: 'exercises/new/074.jpg' },
  { name: 'Планка', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '45 сек', defaultLoad: 'вес тела', technique: 'Прямая линия от плеч до пяток, таз не проваливается.', equipment: '-', imageUrl: 'exercises/new/058.jpg' },
  { name: 'Русские скручивания', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '20 (по 10 на сторону)', defaultLoad: '6 кг', technique: 'Корпус под 45°, повороты за счёт косых мышц.', equipment: 'Диск/гиря', imageUrl: 'exercises/new/060.jpg' },
  { name: 'Скручивания на блоке', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '15', defaultLoad: '30 кг', technique: 'Скручивание корпуса вниз к бёдрам, таз неподвижен.', equipment: 'Блочный тренажёр', imageUrl: 'exercises/new/075.jpg' },
  { name: 'Бег на дорожке', muscleGroup: 'CARDIO', defaultSets: 1, defaultReps: '20 мин', defaultLoad: 'пульс 130-150', technique: 'Равномерный темп, приземление на середину стопы.', equipment: 'Беговая дорожка', imageUrl: 'exercises/new/070.jpg' },
  { name: 'Гребной тренажёр', muscleGroup: 'CARDIO', defaultSets: 1, defaultReps: '15 мин', defaultLoad: '20 уд/мин', technique: 'Тяга ногами → корпусом → руками, возврат в обратном порядке.', equipment: 'Гребной тренажёр', imageUrl: 'exercises/new/076.jpg' },
  { name: 'Велотренажёр', muscleGroup: 'CARDIO', defaultSets: 1, defaultReps: '25 мин', defaultLoad: 'уровень 8', technique: 'Седло по высоте бедра, каденс 80-90 об/мин.', equipment: 'Велотренажёр', imageUrl: 'exercises/new/071.jpg' },
  { name: 'Скакалка', muscleGroup: 'CARDIO', defaultSets: 5, defaultReps: '1 мин', defaultLoad: '-', technique: 'Прыжки на низкой амплитуде, приземление на носки.', equipment: 'Скакалка' },
  { name: 'Берпи', muscleGroup: 'CARDIO', defaultSets: 4, defaultReps: '15', defaultLoad: 'вес тела', technique: 'Присед-упор лёжа-отжимание-прыжок вверх без пауз.', equipment: '-', imageUrl: 'exercises/new/078.jpg' },
  { name: 'Эллиптический тренажёр', muscleGroup: 'CARDIO', defaultSets: 1, defaultReps: '20 мин', defaultLoad: 'уровень 6', technique: 'Плавное движение без ударной нагрузки на суставы.', equipment: 'Эллипсоид', imageUrl: 'exercises/new/079.jpg' },
  { name: 'Становая тяга на прямых ногах', muscleGroup: 'LEGS', defaultSets: 3, defaultReps: '10-12', defaultLoad: '40 кг', technique: 'Минимальный изгиб коленей, акцент на заднюю поверхность бедра.', equipment: 'Штанга', imageUrl: 'exercises/new/080.jpg' },
  { name: 'Жим Арнольда', muscleGroup: 'SHOULDERS', defaultSets: 3, defaultReps: '10', defaultLoad: '12 кг', technique: 'Разворот кистей от себя к вверх при подъёме гантелей.', equipment: 'Гантели', imageUrl: 'exercises/new/081.jpg' },
  { name: 'Тяга Т-грифа', muscleGroup: 'BACK', defaultSets: 3, defaultReps: '10-12', defaultLoad: '40 кг', technique: 'Корпус фиксирован под углом, тяга к груди/животу.', equipment: 'Т-гриф', imageUrl: 'exercises/new/017.jpg' },
  { name: 'Жим в тренажёре Смита', muscleGroup: 'CHEST', defaultSets: 3, defaultReps: '10-12', defaultLoad: '50 кг', technique: 'Траектория грифа фиксирована, контроль негативной фазы.', equipment: 'Тренажёр Смита', imageUrl: 'exercises/new/082.jpg' },
  { name: 'Сгибание рук на скамье Скотта', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '10-12', defaultLoad: '18 кг', technique: 'Плечо плотно прижато к пюпитру, без читинга.', equipment: 'Скамья Скотта', imageUrl: 'exercises/new/048.jpg' },
  { name: 'Кубинский жим', muscleGroup: 'SHOULDERS', defaultSets: 3, defaultReps: '12', defaultLoad: '7 кг', technique: 'Протяжка-ротация-жим одним плавным движением.', equipment: 'Гантели', imageUrl: 'exercises/new/083.jpg' },
  { name: 'Боковая планка', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '30 сек на сторону', defaultLoad: 'вес тела', technique: 'Тело прямой линией, таз не провисает.', equipment: '-', imageUrl: 'exercises/new/084.jpg' },
  { name: 'Приседания в тренажёре Смита', muscleGroup: 'LEGS', defaultSets: 4, defaultReps: '10-12', defaultLoad: '60 кг', technique: 'Стопы чуть впереди грифа для вертикальной траектории.', equipment: 'Тренажёр Смита', imageUrl: 'exercises/new/092.jpg' },
  { name: 'Шраги со штангой', muscleGroup: 'BACK', defaultSets: 3, defaultReps: '12-15', defaultLoad: '40 кг', technique: 'Подъём плеч строго вверх, без вращения.', equipment: 'Штанга', imageUrl: 'exercises/new/040.jpg' },
  // Дополнительно из открытой базы wger.de (с фото)
  { name: 'Жим гантелей лёжа', muscleGroup: 'CHEST', defaultSets: 4, defaultReps: '10-12', defaultLoad: '20 кг', technique: 'Гантели движутся по дуге, в верхней точке почти соприкасаются.', equipment: 'Гантели, скамья', imageUrl: 'exercises/new/002.jpg' },
  { name: 'Жим штанги на наклонной скамье', muscleGroup: 'CHEST', defaultSets: 4, defaultReps: '8-10', defaultLoad: '50 кг', technique: 'Наклон скамьи 30-45°, гриф опускается к верху груди.', equipment: 'Штанга, наклонная скамья', imageUrl: 'exercises/003-жим-штанги-на-наклонной-скамье.jpg', imageAttribution: 'wger.de, CC-BY-SA 3.0, автор: Everkinetic' },
  { name: 'Жим штанги на скамье с отрицательным наклоном', muscleGroup: 'CHEST', defaultSets: 3, defaultReps: '8-10', defaultLoad: '55 кг', technique: 'Ноги зафиксированы, гриф опускается к нижней части груди.', equipment: 'Штанга, скамья', imageUrl: 'exercises/new/005.jpg' },
  { name: 'Жим в тренажёре (грудь)', muscleGroup: 'CHEST', defaultSets: 3, defaultReps: '10-12', defaultLoad: '40 кг', technique: 'Спина плотно прижата к спинке, амплитуда полная, без рывка.', equipment: 'Тренажёр', imageUrl: 'exercises/new/010.jpg' },
  { name: 'Подтягивания обратным хватом', muscleGroup: 'BACK', defaultSets: 3, defaultReps: '6-10', defaultLoad: 'вес тела', technique: 'Узкий обратный хват, акцент на бицепс и низ широчайших.', equipment: 'Турник', imageUrl: 'exercises/013-подтягивания-обратным-хватом.png', imageAttribution: 'wger.de, CC-BY-SA 3.0, автор: Everkinetic' },
  { name: 'Тяга гантели в наклоне одной рукой', muscleGroup: 'BACK', defaultSets: 3, defaultReps: '10-12', defaultLoad: '20 кг', technique: 'Одна рука и колено опираются на скамью, тяга гантели к поясу.', equipment: 'Гантель, скамья', imageUrl: 'exercises/new/015.jpg' },
  { name: 'Тяга горизонтального блока', muscleGroup: 'BACK', defaultSets: 3, defaultReps: '10-12', defaultLoad: '45 кг', technique: 'Спина прямая, тяга рукояти к животу, лопатки сводятся в конце.', equipment: 'Блочный тренажёр', imageUrl: 'exercises/new/016.jpg' },
  { name: 'Тяга верхнего блока узким хватом', muscleGroup: 'BACK', defaultSets: 3, defaultReps: '10-12', defaultLoad: '45 кг', technique: 'Тяга к верху груди, локти вниз, без раскачки корпуса.', equipment: 'Блочный тренажёр', imageUrl: 'exercises/new/018.jpg' },
  { name: 'Пуловер на верхнем блоке прямыми руками', muscleGroup: 'BACK', defaultSets: 3, defaultReps: '12-15', defaultLoad: '25 кг', technique: 'Руки прямые, тяга рукояти вниз по дуге за счёт широчайших.', equipment: 'Блочный тренажёр', imageUrl: 'exercises/020-пуловер-на-верхнем-блоке-прямыми-руками.jpg', imageAttribution: 'wger.de, CC-BY-SA 4.0, автор: barry' },
  { name: 'Фронтальные приседания', muscleGroup: 'LEGS', defaultSets: 4, defaultReps: '8-10', defaultLoad: '50 кг', technique: 'Штанга на передних дельтах, корпус вертикально, присед глубокий.', equipment: 'Штанга, стойки', imageUrl: 'exercises/new/022.jpg' },
  { name: 'Становая тяга сумо', muscleGroup: 'LEGS', defaultSets: 4, defaultReps: '6-8', defaultLoad: '70 кг', technique: 'Широкая постановка ног, носки в стороны, гриф по центру стоп.', equipment: 'Штанга', imageUrl: 'exercises/new/024.jpg' },
  { name: 'Сгибание ног в тренажёре', muscleGroup: 'LEGS', defaultSets: 3, defaultReps: '12-15', defaultLoad: '35 кг', technique: 'Таз плотно прижат, сгибание без рывка, полная амплитуда.', equipment: 'Тренажёр', imageUrl: 'exercises/new/027.jpg' },
  { name: 'Выпады', muscleGroup: 'LEGS', defaultSets: 3, defaultReps: '12 на ногу', defaultLoad: 'вес тела', technique: 'Колено передней ноги над носком, заднее колено почти касается пола.', equipment: '-', imageUrl: 'exercises/new/028.jpg' },
  { name: 'Болгарские выпады', muscleGroup: 'LEGS', defaultSets: 3, defaultReps: '10-12 на ногу', defaultLoad: 'вес тела', technique: 'Задняя нога на скамье, присед на передней ноге, колено не выходит за носок.', equipment: 'Скамья', imageUrl: 'exercises/new/029.jpg' },
  { name: 'Зашагивания на платформу', muscleGroup: 'LEGS', defaultSets: 3, defaultReps: '12 на ногу', defaultLoad: '10 кг', technique: 'Полное разгибание опорной ноги вверху, без толчка второй ногой.', equipment: 'Платформа/скамья', imageUrl: 'exercises/new/030.jpg' },
  { name: 'Ягодичный мост', muscleGroup: 'LEGS', defaultSets: 3, defaultReps: '15-20', defaultLoad: 'вес тела', technique: 'Таз поднимается до прямой линии колени-таз-плечи, пауза вверху.', equipment: '-', imageUrl: 'exercises/new/031.jpg' },
  { name: 'Мах гирей', muscleGroup: 'LEGS', defaultSets: 4, defaultReps: '15-20', defaultLoad: '16 кг', technique: 'Толчок тазом вперёд, гиря движется за счёт бёдер, не рук.', equipment: 'Гиря', imageUrl: 'exercises/new/032.jpg' },
  { name: 'Подъём на носки в тренажёре для жима ногами', muscleGroup: 'LEGS', defaultSets: 4, defaultReps: '15-20', defaultLoad: '80 кг', technique: 'Носки на нижнем крае платформы, подъём за счёт икр.', equipment: 'Тренажёр', imageUrl: 'exercises/new/034.jpg' },
  { name: 'Жим штанги сидя', muscleGroup: 'SHOULDERS', defaultSets: 4, defaultReps: '8-10', defaultLoad: '30 кг', technique: 'Спина плотно к спинке, гриф движется строго вертикально.', equipment: 'Штанга, скамья', imageUrl: 'exercises/new/035.jpg' },
  { name: 'Подъём гантелей перед собой', muscleGroup: 'SHOULDERS', defaultSets: 3, defaultReps: '12-15', defaultLoad: '8 кг', technique: 'Подъём до уровня плеч, без раскачки корпуса.', equipment: 'Гантели', imageUrl: 'exercises/new/038.jpg' },
  { name: 'Шраги с гантелями', muscleGroup: 'SHOULDERS', defaultSets: 3, defaultReps: '12-15', defaultLoad: '20 кг', technique: 'Подъём плеч строго вверх, пауза в верхней точке.', equipment: 'Гантели', imageUrl: 'exercises/new/041.jpg' },
  { name: 'Жим штанги толчком', muscleGroup: 'SHOULDERS', defaultSets: 3, defaultReps: '6-8', defaultLoad: '35 кг', technique: 'Лёгкий подсед и выталкивание ногами помогает вывести штангу вверх.', equipment: 'Штанга', imageUrl: 'exercises/new/042.jpg' },
  { name: 'Тяга гантелей к подбородку', muscleGroup: 'SHOULDERS', defaultSets: 3, defaultReps: '10-12', defaultLoad: '12 кг', technique: 'Локти ведут движение и идут выше кистей.', equipment: 'Гантели', imageUrl: 'exercises/new/044.jpg' },
  { name: 'Подъём гантелей на бицепс', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '10-12', defaultLoad: '12 кг', technique: 'Локти прижаты к корпусу, супинация кисти в верхней точке.', equipment: 'Гантели', imageUrl: 'exercises/new/046.jpg' },
  { name: 'Сгибание рук на нижнем блоке', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '12-15', defaultLoad: '20 кг', technique: 'Локти зафиксированы, движение только в предплечье.', equipment: 'Блочный тренажёр', imageUrl: 'exercises/049-сгибание-рук-на-нижнем-блоке-фото.png', imageAttribution: 'wger.de, CC-BY-SA 3.0, автор: Everkinetic' },
  { name: 'Французский жим лёжа', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '10-12', defaultLoad: '20 кг', technique: 'Локти неподвижны, гриф опускается за голову, растяжка трицепса.', equipment: 'EZ-гриф', imageUrl: 'exercises/new/050.jpg' },
  { name: 'Разгибание рук лёжа EZ-грифом', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '10-12', defaultLoad: '20 кг', technique: 'Локти статичны, гриф опускается ко лбу, разгибание за счёт трицепса.', equipment: 'EZ-гриф, скамья', imageUrl: 'exercises/new/051.jpg' },
  { name: 'Разгибание рук на верхнем блоке', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '12-15', defaultLoad: '25 кг', technique: 'Локти прижаты к корпусу, полное разгибание с паузой.', equipment: 'Блочный тренажёр', imageUrl: 'exercises/new/052.jpg' },
  { name: 'Отжимания между скамьями', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '12-15', defaultLoad: 'вес тела', technique: 'Руки на краю скамьи, сгибание локтей до 90°, акцент на трицепс.', equipment: 'Скамья', imageUrl: 'exercises/053-отжимания-между-скамьями-фото.png', imageAttribution: 'wger.de, CC-BY-SA 3.0, автор: Everkinetic' },
  { name: 'Жим штанги узким хватом', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '8-10', defaultLoad: '40 кг', technique: 'Кисти чуть уже плеч, локти движутся вдоль корпуса.', equipment: 'Штанга, скамья', imageUrl: 'exercises/new/054.jpg' },
  { name: 'Подъём штанги обратным хватом', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '10-12', defaultLoad: '20 кг', technique: 'Хват сверху, акцент на предплечья и плечелучевую мышцу.', equipment: 'Штанга', imageUrl: 'exercises/new/055.jpg' },
  { name: 'Кистевой эспандер', muscleGroup: 'ARMS', defaultSets: 3, defaultReps: '15-20', defaultLoad: '-', technique: 'Сжатие эспандера, статическая пауза 1-2 сек в сжатом положении.', equipment: 'Эспандер', imageUrl: 'exercises/056-кистевой-эспандер.png', imageAttribution: 'wger.de, CC-BY-SA 4.0' },
  { name: 'Скручивания', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '15-20', defaultLoad: 'вес тела', technique: 'Скручивание за счёт пресса, поясница прижата к полу.', equipment: 'Коврик', imageUrl: 'exercises/new/057.jpg' },
  { name: 'Подъём ног лёжа', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '12-15', defaultLoad: 'вес тела', technique: 'Ноги прямые, подъём без рывка, поясница прижата к полу.', equipment: 'Коврик', imageUrl: 'exercises/new/059.jpg' },
  { name: 'Косые скручивания', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '15-20 на сторону', defaultLoad: 'вес тела', technique: 'Скручивание к тазу по диагонали, акцент на косые мышцы.', equipment: 'Коврик', imageUrl: 'exercises/new/061.jpg' },
  { name: 'Уголок-лодочка', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '30-40 сек', defaultLoad: 'вес тела', technique: 'Поясница прижата к полу, руки и ноги на весу.', equipment: 'Коврик', imageUrl: 'exercises/new/062.jpg' },
  { name: 'Подъём коленей в висе', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '12-15', defaultLoad: 'вес тела', technique: 'Подъём коленей к груди без раскачки корпуса.', equipment: 'Турник', imageUrl: 'exercises/new/063.jpg' },
  { name: 'Ролик для пресса', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '10-12', defaultLoad: 'вес тела', technique: 'Раскат вперёд с прямой спиной, возврат за счёт пресса.', equipment: 'Ролик', imageUrl: 'exercises/new/064.jpg' },
  { name: 'Планка на предплечьях', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '45-60 сек', defaultLoad: 'вес тела', technique: 'Локти под плечами, тело прямой линией, таз не проваливается.', equipment: 'Коврик', imageUrl: 'exercises/065-планка-на-предплечьях-фото.png', imageAttribution: 'wger.de, CC-BY-SA 4.0' },
  { name: 'Антиротационный жим на блоке', muscleGroup: 'ABS', defaultSets: 3, defaultReps: '12-15 на сторону', defaultLoad: '15 кг', technique: 'Жим рукояти вперёд, корпус сопротивляется вращению.', equipment: 'Блочный тренажёр', imageUrl: 'exercises/new/066.jpg' },
  { name: 'Прыжки с высоким подниманием колен', muscleGroup: 'CARDIO', defaultSets: 4, defaultReps: '30 сек', defaultLoad: '-', technique: 'Быстрая смена ног в прыжке, колени выше пояса.', equipment: '-', imageUrl: 'exercises/067-прыжки-с-высоким-подниманием-колен-фото.png', imageAttribution: 'wger.de, CC-BY-SA 4.0' },
  { name: 'Прыжки "звёздочка"', muscleGroup: 'CARDIO', defaultSets: 4, defaultReps: '30-40', defaultLoad: '-', technique: 'Одновременный разброс рук и ног в прыжке, приземление мягкое.', equipment: '-', imageUrl: 'exercises/068-прыжки-звёздочка-фото.png', imageAttribution: 'wger.de, CC-BY-SA 4.0' },
  { name: 'Бег с высоким подниманием колен', muscleGroup: 'CARDIO', defaultSets: 4, defaultReps: '30 сек', defaultLoad: '-', technique: 'Активная работа рук, колени поднимаются выше пояса.', equipment: '-', imageUrl: 'exercises/new/069.jpg' },
];
